import { Header } from "@/components/layout/Header"
import "./globals.css"
import type { Metadata } from "next"
import { ProductSidebar } from "@/app/products/ProductSidebar"
import { PageLoading } from "@/components/PageLoading"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="bg-slate-100">
                <Header isLogin={true} />
                <div className="flex flex-row mt-16">
                    <ProductSidebar />
                    <div className="container w-auto -mt-9">{children}</div>
                </div>
            </body>
        </html>
    )
}
