import { Header } from "@/components/layout/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Sidebar } from "@/components/layout/Sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <section>
                    <Header></Header>
                    <Sidebar></Sidebar>
                </section>

                <div className="container ml-56 w-auto">{children}</div>
            </body>
        </html>
    )
}
